services:
  shell:
    build: .
    image: opendsm
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - .:/app

  test:
    image: opendsm
    entrypoint: py.test -n0
    volumes:
      - .:/app
      - /app/tests/__pycache__/

  uv:
    image: opendsm
    entrypoint: uv
    volumes:
      - .:/app

  blacken:
    image: opendsm
    entrypoint: black .
    volumes:
      - .:/app
