[tox]
envlist = 3.{10, 11, 12}

[testenv]
deps =
    pytest
    pytest-cov
    pytest-xdist
    syrupy>=5,<6
setenv =
    OMP_NUM_THREADS = 1
    MKL_NUM_THREADS = 1
    OPENBLAS_NUM_THREADS = 1
    NUMEXPR_NUM_THREADS = 1
commands =
    pytest tests/